changelog.md
sportorg/config.py
versioninfo.json

+ Automatical database saving while new finish or readout
+ Automatical SPORTident station connection
+ Remember the last used directory
+ Opening of recent file
+ Submenu "Recent files"
+ Templates (start list, results) were updated
+ Automatical split printing while readout
- "Open with" option for *.sportorg extention
- Mixing several groups while tossing
- Winorient import - splits import was fixed

Added changelog and changed the version of the program

---

sportorg/modules/sportident/sireader.py

Using `/dev/Sx` or `/dev/ttyUSBx` for SIreader on Linux.

Port list depend on platform (Linux or Windows)

---

templates/start/4_bib.html

Комит решает проблему на половину пустой первой страницы при печати номеров.

Templates bib: remove body margin

---

languages/ru_RU/LC_MESSAGES/sportorg.po
sportorg/gui/main_window.py
sportorg/gui/menu/actions.py
sportorg/gui/menu/factory.py
sportorg/gui/menu/menu.py
sportorg/models/memory.py
sportorg/models/start/start_preparation.py

- Using QTimer instead QThread in main_window.py (prevent error: `QThread: Destroyed while thread is still running`).
- Added action "Use card number as bib".
- Added CP range for course settings (e. g. `*(31-35)`)

Fix QThread crash, CP range, card number as bib

---

sportorg/libs/template/template.py
sportorg/modules/backup/json.py

Кириллические значения в файле сохранения и в протоколе старта / результатов сохраняются в unicode вместо \uXXXX ескейп-последовательностей. Появляется возможность быстро найти или внести исправление в протокол или в базу в текстовом редакторе, не запуская SportOrg.
Обратная совместимость сохраняется: старые json-файлы открываются в новом SportOrg, новые json-файлы открываются в старом SportOrg.

Cyrillic values in json are stored as unicode

---

languages/ru_RU/LC_MESSAGES/sportorg.po

Падает test_duplicates из-за дубрирующейся строки _Ignore readout before start_. 
После удаления дубля тест выполняется.

Fix broken test_duplicates

---

languages/ru_RU/LC_MESSAGES/sportorg.po
sportorg/gui/dialogs/result_edit.py
sportorg/gui/dialogs/timekeeping_properties.py
sportorg/gui/menu/actions.py
sportorg/libs/template/template.py
sportorg/models/memory.py
sportorg/models/result/result_checker.py
sportorg/modules/printing/printout_split.py
sportorg/modules/sportident/result_generation.py
templates/split/1_split_printout.html
templates/split/2_marked_route_penalty_A5.html
templates/split/3_marked_route_penalty_80mm.html
tests/test_penalty_checking.py

Мои наработки для маркировки со штрафными кругами (на пункте оценки печатается штраф, спортсмен проезжает требуемое количество штрафных кругов, отмечаясь на станции, может быть дисквалифицирован если проехал меньше, чем надо). Работу над проверкой маркировки параллельно вёл @sergeikobelev и его изменения попали в master. Соответственно, часть моих изменений перестали быть актуальными.
* `Настройки хронометража` -> `Штраф`. Переключение настроек в активное / не активное состояние в зависимости от выбранных настроек
* `Настройки хронометража` -> `Штраф`. Добавлены всплывающие подсказки (ToolTip) к некоторым настройкам
* Добавлен `ResultStatus.MISS_PENALTY_LAP` (пп4.6.12.7 # не прошел назначенное число штрафных кругов)
* `check_penalty_laps()` — проверка количества штрафных кругов. …

Наработки для маркированной трассы со штрафными кругами

---

languages/en_US/LC_MESSAGES/sportorg.po
languages/ru_RU/LC_MESSAGES/sportorg.po

Короткие названия вкладок в окне Опции -> Настройки хронометража. 
В текущей версии Спорторга чтобы попасть во вкладку `Очки` или `Расчет штрафа из сплитов`, нужно либо скроллить вкладки, либо увеличивать размер окна. 
С короткими названиями все вкладки помещаются в окно. Достаточно одного клика, чтобы попасть на нужную вкладку.
Изменение английского перевода вместо изменения оригинальной строки в timekeeping_properties.py — чтобы не было повтора строки "Result".

fix: shorter tab titles in the settings window

---

CONTRIBUTING.md
README.md
pyproject.toml

Актуализировал руководство по настройке окружения и запуску SportOrg из исходного кода. 
Проверил на чистой Windows 10, в том числе и с уже установленным более свежим python (возможно, нужно более акцентированно написать о необходимости установки python 3.8). Могут возникнуть проблемы с установкой poetry и poe, если системный python установлен через Microsoft Store — он не прописывает себя в переменной окружения PATH, с терминалом взаимодействует как-то по-другому.
В `pyproject.toml` задание `poe run` добавил создание mo-файлов, без них SportOrg падает с ошибкой.
Английский не родной. Возможно, в тексте есть ошибки.

docs: actual run from source tutorial

---

languages/ru_RU/LC_MESSAGES/sportorg.po
sportorg/gui/dialogs/filter_dialog.py
sportorg/gui/tabs/memory_model.py
tests/test_memory_model.py

В фильтр добавлен пункт «не содержит» (по мотивам обсуждения #427). Добавлены тесты.
Регулярное выражение для «не содержит» взято отсюда: https://stackoverflow.com/questions/717644/regular-expression-that-doesnt-contain-certain-string
Вопрос по фильтру. Не лучше вместо регулярных выражений ли использовать `==`, `in`, `not in`?

feat: add does-not-contain action to the filter

---

sportorg/modules/live/orgeo.py

`result['penalty_time']` при выключенном штрафе инициализируется как Null, сравнение не выполняется и json не формируется

fix: fix online

---

sportorg/gui/dialogs/entry_mass_edit.py
sportorg/gui/dialogs/merge_results.py
sportorg/gui/dialogs/person_edit.py
sportorg/gui/dialogs/result_edit.py
sportorg/gui/dialogs/settings.py
sportorg/gui/dialogs/text_io.py
sportorg/gui/menu/actions.py
sportorg/gui/tabs/memory_model.py
sportorg/models/memory.py
sportorg/models/start/relay.py
sportorg/models/start/start_preparation.py
sportorg/modules/backup/json.py
sportorg/modules/iof/iof_xml.py
sportorg/modules/recovery/recovery_orgeo_finish_csv.py
sportorg/modules/sportident/result_generation.py
sportorg/modules/winorient/wdb.py
sportorg/modules/winorient/winorient.py

Починил (надеюсь) индекс номеров участников и чипов. 
Доступ к номеру участника и чипу сделал через getter/setter и убрал change_bib() — для исключения случайного присваивания без изменения индекса.
Обновление индекса при удалении спортсменов.
Обнаружил, что при открытии базы с несколькими днями, пересчёт результатов/сплитов происходит только для текущего дня, для остальных дней пересчёта не происходит. Сделал, чтобы индексы создавались для всех дней. Не возникнет ли проблема с проверкой отметки — не знаю.
В некоторых случаях возможны одинаковые номера и одинаковые чипы (жеребьёвка, массовое редактирование). Добавил сообщение в логи.
Дублирующиеся номера/чипы — потенциально неприятный момент. Если создали участника с дублирующимся чипом, а затем удалили его — этот чип пропадёт из индекса. …

fix: fix bib and card_numbers indexes

---

languages/ru_RU/LC_MESSAGES/sportorg.po
sportorg/gui/dialogs/timekeeping_properties.py
sportorg/models/memory.py
sportorg/models/result/result_calculation.py
sportorg/models/result/result_checker.py
sportorg/modules/live/orgeo.py
sportorg/modules/printing/printing.py
sportorg/modules/printing/printout_split.py
templates/reports/1_протокол_результатов.html
templates/reports/1_протокол_результатов_сплиты.html
templates/reports/1_протокол_результатов_термопринтер_80_мм.html
templates/reports/ENG_1_results.html
templates/split/1_split_printout.html
tests/test_result_checking.py

* Штраф за превышение вренмени гонки (контрольное время в настройках группы). Штраф ограничен полными очками (во избежание отрицательного результата)
* Дисквалификация за превышение контрольного времени: время гонки + максимальное превшение. Добавлено поле в настройках хронометража для задания максимального превышения  (по умолчанию 30 минут)
* Сокрытие блока рогейна, если выбран другой способ определения результата. Окно с настройками хронометража стало слишком большим, не влезает на маленьких экранах или при малых размерах окна спорторга
* Отправка результата рогейна вместе с очками в онлайн (на оргео)
* Протоколы результатов рогейна. Выводятся полное количество очков, штраф, итоговое количество очков (полное минус штраф) и время. Исправлена сортировка при построении протоколов по …

feat: rogaine (calculate penalty, send scores online, print results and splits)

---

languages/ru_RU/LC_MESSAGES/sportorg.po
sportorg/gui/dialogs/live_dialog.py
sportorg/gui/dialogs/settings.py
sportorg/modules/live/orgeo.py

= Подкорректирована опечатка в label для режима проверки отметки ARDF
+ Добавлена новая опция в настройках Live с возможностью отправлять все содержимое чипа, т.к. не всегда в онлайне нужно выводить только то что пройдено по самой дистанции.

Correct ardf label and send online all controls (option)

---

sportorg/gui/main_window.py
sportorg/gui/menu/actions.py
sportorg/models/memory.py

В базе могут содержаться дублирующиеся номера и чипы. Если из двух дублирующихся удалить индексированного участника, второй остаётся не индексированным. И не находится, например, при считывании чипа. При этом секретарь точно знает, что участник с таким номером или чипом точно есть в базе. Стрессовая ситуация, секретарь может не придумать, что делать.
Делаю перестройку индекса после основных операций, при которых возможно удаление индекса.
Также в логах отражается, какой из двух участников с дублирующимимя номерами / чипами проиндексирован, а какой нет.
Выявленный побочный эффект. Если есть участники с дублирующимися номерами / чипами, они могут быть проиндексированы по-разному в зависимости от сортировки вкладки Участники. Правильнее, если бы индексация сохранялась.
Повторяющиеся …

fix: rebuild indexes after major changing/deleting bibs and cards operations

---

languages/ru_RU/LC_MESSAGES/sportorg.po
sportorg/gui/dialogs/event_properties.py
sportorg/gui/dialogs/group_edit.py
sportorg/gui/dialogs/group_mass_edit.py
sportorg/models/memory.py
sportorg/models/result/result_calculation.py
tests/test_relay_results.py

Issue #442 
Добавлена поддержка международного принципа на эстафетах. 
- Добавлена настройка группы. Часть групп могут быть обработаны по международному принципу, часть по обычному
- Исправлен баг: настройка группы RaceType = RaceType.RELAY не сохранялась в json-файле
На будущее:
- Привести в соответствие пунктам правил 7.2.4.1.1 / 7.2.4.1.2 последовательность дисквалифицированных команд
- Отправка результатов онлайн (orgeo может сортировать команды по очкам `Настройки хронометража -> Очки`), однако а) очки вычисляются только на этапе протокола результатов; б) необходимо отправлять результаты всех участников эстафетной команды и всех команд, у которых изменились места после считывания участника (считываться могут не в порядке финиша).

feat: relay mode: best team placing

---

sportorg/gui/menu/actions.py

Работа с онлайн, задача: обновить все (или часть) результатов. 
Действие: Выделить все результаты (Ctrl+A), отправить онлайн (Ctrl+K).
Ранее: результаты отправлялись «сверху» «вниз»: сначала самые свежие результаты, затем самые старые. В блоке «последних результатах» на orgeo появлялись результаты первых финишировавших. Если секретарь хочет, чтобы отправка результатов не влияла на блок «последние результаты», надо или сортировать результаты перед отправкой, или после отправки по одному отправлять шесть последних результатов.
Сейчас: «верхние» (последние) результаты отправляются последними, в блоке «последние результаты» содержатся шесть последних финишей.

fix: send results online in correct order (not reversed)

---

sportorg/modules/sportident/sireader.py

On MacOs and Linux searching serial devices so fast, but on windows very very slow - this commit fixed it

perf: acceleration of searching for COM ports in the windows system

---

sportorg/gui/main_window.py

Исправлена ошибка: отсутствие импорта `ResultCalculation()`.
Вызовы `ResultChecker()` и `ResultCalculation()` заменены на вызов `recalculate_results()`

fix: fix result check in multiday mode

---

sportorg/gui/dialogs/print_properties.py
sportorg/gui/dialogs/report_dialog.py
sportorg/gui/utils/custom_controls.py

Исправлено поведение поля выбора шаблонов для печати сплитов и протоколов
Ранее у диалоговых окон печати протоколов и настроек печати при открытии устанавливался размер, соответствующий самому длинному названию шаблона. Если в папке лежал шаблон с длинным именем, диалоговые окна становились непропорционально широкими, их ширину нельзя было уменьшить. Ранее было черновое исправление такого поведения (#499)
Теперь можно задавать минимальную (в пикселях) и рекомендуемую (в символах) ширину поля выбора. Значения 160, 32 и 250, 60 подобраны для лучшего выбора наиболее популярных шаблонов

fix: fix AdvComboBox behaviour
